# docker running file
# use "docker-compose up" to run
version: '3.9'
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment: 
      MYSQL_DATABASE: rahul
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbData:/var/lib/mysql
    ports:
      - "3306:3306"